sudo: required

matrix:
  include:
    - language: java
      install: true
      jdk:
        - oraclejdk8
      os: osx
      osx_image: xcode9.4
      before_install:
        - brew update
        - brew tap caskroom/versions
        - brew cask install java8
        - export JAVA_HOME=`/usr/libexec/java_home -v 1.8`
        - java -version
        - brew outdated xctool || brew upgrade xctool
        - npm install -g appium
      script:
      - mvn clean site install -Dmaven.test.skip=true
      - Platform="ios" mvn clean -Dtest=Runner test