sudo: required

matrix:
  include:
    - language: java
      jdk:
        - oraclejdk8
      os: osx
      osx_image: xcode9.4
      before_install:
        - brew update
        - brew outdated xctool || brew upgrade xctool
        - xcrun simctl list -j devices
        - npm install -g appium
      script:
      - mvn clean site install -Dmaven.test.skip=true
      - Platform="ios" mvn clean -Dtest=Runner test