# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

pool:
  vmImage: 'macOS 10.13'

steps:
- script: |
    brew outdated xctool || brew upgrade xctool
    adb --version
    /Users/vsts/Library/Android/sdk/tools/bin/sdkmanager --list
    /Users/vsts/Library/Android/sdk/tools/bin/sdkmanager "system-images;android-27;default;x86_64"
    echo no | /Users/vsts/Library/Android/sdk/tools/bin/avdmanager  create avd -c 100M -n test -k 'system-images;android-27;google_apis;x86'
    /Users/vsts/Library/Android/sdk/tools/bin/avdmanager list avd
    emulator -avd test -no-skin -no-window &
    adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done;'
    adb devices
  displayName: 'Build with Maven'